version: "3.9"

services:
  blog-app:
    container_name: ${PUBLIC_FRONTEND_MAIN_APP_HOST}
    build:
      dockerfile: ./frontend/apps/blog/.dockerfile
    ports:
      - "${PUBLIC_FRONTEND_BLOG_APP_PORT}:3000"
    volumes:
      - "./frontend/apps/blog/app:/app/frontend/apps/blog/app"
      - "./frontend/apps/blog/public:/app/frontend/apps/blog/public"
      # - "./frontend/apps/main/components:/app/frontend/apps/main/components"
      # - "./frontend/apps/main/context:/app/frontend/apps/main/context"
      # - "./frontend/apps/main/data:/app/frontend/apps/main/data"
      # - "./frontend/apps/main/helpers:/app/frontend/apps/main/helpers"
      # - "./frontend/apps/main/public:/app/frontend/apps/main/public"
      # - "./frontend/apps/main/types:/app/frontend/apps/main/types"
      # - "./frontend/apps/main/widgets:/app/frontend/apps/main/widgets"
      # - "./frontend/apps/main/theme.ts:/app/frontend/apps/main/theme.ts"
  platform-app:
    container_name: ${PUBLIC_FRONTEND_PLATFORM_APP_HOST}
    build:
      dockerfile: ./frontend/apps/platform/.dockerfile
    ports:
      - "${PUBLIC_FRONTEND_PLATFORM_APP_PORT}:5173"
    volumes:
      - "./frontend/apps/platform/src:/app/frontend/apps/platform/src"
      - "./frontend/apps/platform/public:/app/frontend/apps/platform/public"
